### ISSUE TITLE
Need support for MQTT Authentication

### ISSUE THREAD

**Issue by brent20** [ragingcomputer/amridm2mqtt#1]
I'm using a basic username and password for my MQTT Broker (while it may not be as important), would it be possible to add MQTT Credentials for authentication? 

Thanks!

**Comment by ragingcomputer** [comment]
Good idea! See commit 9224489. Give it a go and let me know if it works!

Username/Password auth is only enabled when both MQTT_USER and MQTT_PASSWORD are specified in settings.py

When both MQTT_USER and MQTT_PASSWORD are not specified in settings.py, it sets auth to None (for wide-open setups like mine)

I tested it with mosquitto on my network and it seems to work both with and without auth enabled now.

**Comment by brent20** [comment]
Works great! Thanks! I started to see meter data flow into my MQTT Broker and then I filled in my serial number hoping to see it broadcast soon. Thanks again for porting this awesome code over to MQTT!
